INSERT INTO series (title, author_id, subgenre_id) VALUES (NULL,NULL,NULL), (NULL,NULL,NULL);

INSERT INTO subgenres (name) VALUES (NULL), (NULL);

INSERT INTO authors (name) VALUES (NULL), (NULL);

INSERT INTO books (title, year, series_id) VALUES
(NULL, NULL, NULL),
(NULL, NULL, NULL),
(NULL, NULL, NULL),
(NULL, NULL, NULL),
(NULL, NULL, NULL),
(NULL, NULL, NULL);

INSERT INTO characters (name, species, motto, author_id) VALUES
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL);

INSERT INTO character_books (book_id, character_id) VALUES
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL),
(NULL, NULL);